name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    types: [ closed ]
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # x를 사용하여 해당 범위 내의 최신 버전 설치
        node-version: [ 22.x ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.6

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      
      - name: pnpm modules Caching
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ matrix.node-version }}-${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ matrix.node-version }}-${{ runner.os }}-pnpm-store-
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Turbo build Caching
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ matrix.node-version }}-${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ matrix.node-version }}-${{ runner.os }}-turbo-

      - name: Create .env file
        run: |
          cd ./apps/web
          touch .env
          echo '${{ secrets.APPLICATION_PROD }}' > .env
        shell: bash

      - name: Build with Turbo
        run: turbo run build